apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd

bases:
#- github.com/redhat-cop/gitops-catalog/sonarqube8/overlays/plugins?ref=v0.5
- ../../base/jenkins2
- ../../base/nexus2
#- ../../base/sonarqube8

resources:
- cicd-namespace.yaml
